services:
  - type: web
    name: taskflow-backend
    runtime: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.14.0
